### PR TITLE
404Error page Designed && React Router dom applied for defferent pages

### PR DESCRIPTION
**Pull request by Shariar-Hasan**
⚠️⚠️⚠️edit: dear maintainer your repository have a mistake, can you fix it? the topic name should be hacktoberfest.
but in your repository its, showing hactoberfest.
image

and also the label in merging section need to be named hacktoberfest-accepted.
image

thats why your repository is  not listed as the hacktoberfest repository for now, **can you fix it and then merge our pull request**.
i am giving below my progress screen shot in hacktoberfest website

image

The changes i have made in code

- deleted some css
- added some css
- added Home, About, NotFound pages
- designed the Not Found page
- added react-router-dom to route among pages

I hope this contribution is enough for a 🔥hactoberfest-accepted labeled PR merge.🔥

### CODE REVIEW

**Comment by abhishek1561998** [comment]
okay may be some tag issue bro let me check

**Comment by Shariar-Hasan** [comment]
> okay may be some tag issue bro let me check

thanks bro, another thing is the label "hactoberfest-accepted" must be "hacktoberfest-accepted".
can you edit this, so that my Pull request get counted for hactoberfest? 😥😥😥

**Comment by abhishek1561998** [comment]
yes i just fix it

**Comment by Shariar-Hasan** [comment]
thanks bro 💖
it worked 🥳🥳
image

**Pull request merged**
